from collections import Counter

all_lineups = [
  {
    "id": 6308,
    "team": "Giants",
    "gameNumber": 1,
    "date": "2024-03-28T00:00:00",
    "opponent": "Padres",
    "opposingSP": "darviyu01",
    "lhp": False,
    "result": "L",
    "score": "4-6",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "yastrmi01",
    "batting6th": "estrath01",
    "batting7th": "confomi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6309,
    "team": "Giants",
    "gameNumber": 2,
    "date": "2024-03-29T00:00:00",
    "opponent": "Padres",
    "opposingSP": "musgrjo01",
    "lhp": False,
    "result": "W",
    "score": "8-3",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6310,
    "team": "Giants",
    "gameNumber": 3,
    "date": "2024-03-30T00:00:00",
    "opponent": "Padres",
    "opposingSP": "ceasedy01",
    "lhp": False,
    "result": "W",
    "score": "9-6",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "murphto04",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6311,
    "team": "Giants",
    "gameNumber": 4,
    "date": "2024-03-31T00:00:00",
    "opponent": "Padres",
    "opposingSP": "kingmi01",
    "lhp": False,
    "result": "L",
    "score": "4-13",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "bailepa01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6312,
    "team": "Giants",
    "gameNumber": 5,
    "date": "2024-04-01T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "paxtoja01",
    "lhp": True,
    "result": "L",
    "score": "3-8",
    "batting1st": "leeju01",
    "batting2nd": "slateau01",
    "batting3rd": "solerjo01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "murphto04",
    "batting7th": "confomi01",
    "batting8th": "estrath01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6313,
    "team": "Giants",
    "gameNumber": 6,
    "date": "2024-04-02T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "brasiry01",
    "lhp": False,
    "result": "L",
    "score": "4-5",
    "batting1st": "leeju01",
    "batting2nd": "chapmma01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "florewi01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6314,
    "team": "Giants",
    "gameNumber": 7,
    "date": "2024-04-03T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "glasnty01",
    "lhp": False,
    "result": "L",
    "score": "4-5",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6315,
    "team": "Giants",
    "gameNumber": 8,
    "date": "2024-04-05T00:00:00",
    "opponent": "Padres",
    "opposingSP": "ceasedy01",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6316,
    "team": "Giants",
    "gameNumber": 9,
    "date": "2024-04-06T00:00:00",
    "opponent": "Padres",
    "opposingSP": "kingmi01",
    "lhp": False,
    "result": "L",
    "score": "0-4",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "murphto04",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6317,
    "team": "Giants",
    "gameNumber": 10,
    "date": "2024-04-07T00:00:00",
    "opponent": "Padres",
    "opposingSP": "waldrma01",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6318,
    "team": "Giants",
    "gameNumber": 11,
    "date": "2024-04-08T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "willitr01",
    "lhp": False,
    "result": "L",
    "score": "1-8",
    "batting1st": "leeju01",
    "batting2nd": "florewi01",
    "batting3rd": "wadela01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "estrath01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6319,
    "team": "Giants",
    "gameNumber": 12,
    "date": "2024-04-09T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "adonjo01",
    "lhp": False,
    "result": "L",
    "score": "3-5",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6320,
    "team": "Giants",
    "gameNumber": 13,
    "date": "2024-04-10T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "corbipa01",
    "lhp": True,
    "result": "W",
    "score": "7-1",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "confomi01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "murphto04",
    "batting7th": "estrath01",
    "batting8th": "ahmedni01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6321,
    "team": "Giants",
    "gameNumber": 14,
    "date": "2024-04-12T00:00:00",
    "opponent": "Rays",
    "opposingSP": "wagueja01",
    "lhp": False,
    "result": "L",
    "score": "1-2",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6322,
    "team": "Giants",
    "gameNumber": 15,
    "date": "2024-04-13T00:00:00",
    "opponent": "Rays",
    "opposingSP": "pepiory01",
    "lhp": False,
    "result": "W",
    "score": "11-2",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6323,
    "team": "Giants",
    "gameNumber": 16,
    "date": "2024-04-14T00:00:00",
    "opponent": "Rays",
    "opposingSP": "armstsh01",
    "lhp": False,
    "result": "L",
    "score": "4-9",
    "batting1st": "leeju01",
    "batting2nd": "florewi01",
    "batting3rd": "wadela01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "murphto04",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6324,
    "team": "Giants",
    "gameNumber": 17,
    "date": "2024-04-15T00:00:00",
    "opponent": "Marlins",
    "opposingSP": "cabreed02",
    "lhp": False,
    "result": "W",
    "score": "4-3",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6325,
    "team": "Giants",
    "gameNumber": 18,
    "date": "2024-04-16T00:00:00",
    "opponent": "Marlins",
    "opposingSP": "weathry01",
    "lhp": True,
    "result": "L",
    "score": "3-6",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "leeju01",
    "batting4th": "solerjo01",
    "batting5th": "murphto04",
    "batting6th": "chapmma01",
    "batting7th": "confomi01",
    "batting8th": "ahmedni01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6326,
    "team": "Giants",
    "gameNumber": 19,
    "date": "2024-04-17T00:00:00",
    "opponent": "Marlins",
    "opposingSP": "rogertr01",
    "lhp": True,
    "result": "W",
    "score": "3-1",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "leeju01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "bailepa01",
    "batting8th": "ahmedni01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6327,
    "team": "Giants",
    "gameNumber": 20,
    "date": "2024-04-18T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "nelsory01",
    "lhp": False,
    "result": "W",
    "score": "5-0",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "bailepa01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6328,
    "team": "Giants",
    "gameNumber": 21,
    "date": "2024-04-19T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "montgjo01",
    "lhp": True,
    "result": "L",
    "score": "1-17",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "solerjo01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "murphto04",
    "batting7th": "estrath01",
    "batting8th": "fitzgty01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6329,
    "team": "Giants",
    "gameNumber": 22,
    "date": "2024-04-20T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "galleza01",
    "lhp": False,
    "result": "W",
    "score": "7-3",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "florewi01",
    "batting6th": "bailepa01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6330,
    "team": "Giants",
    "gameNumber": 23,
    "date": "2024-04-21T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "ceccosl01",
    "lhp": False,
    "result": "L",
    "score": "3-5",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "florewi01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "bailepa01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6331,
    "team": "Giants",
    "gameNumber": 24,
    "date": "2024-04-22T00:00:00",
    "opponent": "Mets",
    "opposingSP": "quintjo01",
    "lhp": True,
    "result": "W",
    "score": "5-2",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "leeju01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "murphto04",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6332,
    "team": "Giants",
    "gameNumber": 25,
    "date": "2024-04-23T00:00:00",
    "opponent": "Mets",
    "opposingSP": "severlu01",
    "lhp": False,
    "result": "W",
    "score": "5-1",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "bailepa01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6333,
    "team": "Giants",
    "gameNumber": 26,
    "date": "2024-04-24T00:00:00",
    "opponent": "Mets",
    "opposingSP": "manaese01",
    "lhp": True,
    "result": "L",
    "score": "2-8",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "confomi01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "bailepa01",
    "batting7th": "estrath01",
    "batting8th": "fitzgty01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6334,
    "team": "Giants",
    "gameNumber": 27,
    "date": "2024-04-26T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "priesqu01",
    "lhp": False,
    "result": "W",
    "score": "3-0",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "bailepa01",
    "batting7th": "yastrmi01",
    "batting8th": "fitzgty01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6335,
    "team": "Giants",
    "gameNumber": 28,
    "date": "2024-04-27T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "MartA­n PA©rez",
    "lhp": True,
    "result": "L",
    "score": "3-4",
    "batting1st": "slateau01",
    "batting2nd": "florewi01",
    "batting3rd": "leeju01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "confomi01",
    "batting8th": "estrath01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6336,
    "team": "Giants",
    "gameNumber": 29,
    "date": "2024-04-28T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "jonesja09",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "chapmma01",
    "batting4th": "confomi01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6337,
    "team": "Giants",
    "gameNumber": 30,
    "date": "2024-04-30T00:00:00",
    "opponent": "Red Sox",
    "opposingSP": "criswco01",
    "lhp": False,
    "result": "L",
    "score": "0-4",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "chapmma01",
    "batting4th": "confomi01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6338,
    "team": "Giants",
    "gameNumber": 31,
    "date": "2024-05-01T00:00:00",
    "opponent": "Red Sox",
    "opposingSP": "crawfku01",
    "lhp": False,
    "result": "L",
    "score": "2-6",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "murphto04",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6339,
    "team": "Giants",
    "gameNumber": 32,
    "date": "2024-05-02T00:00:00",
    "opponent": "Red Sox",
    "opposingSP": "winckjo01",
    "lhp": False,
    "result": "W",
    "score": "3-1",
    "batting1st": "leeju01",
    "batting2nd": "solerjo01",
    "batting3rd": "florewi01",
    "batting4th": "confomi01",
    "batting5th": "bailepa01",
    "batting6th": "chapmma01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6340,
    "team": "Giants",
    "gameNumber": 33,
    "date": "2024-05-03T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "nolaaa01",
    "lhp": False,
    "result": "L",
    "score": "3-4",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "solerjo01",
    "batting4th": "confomi01",
    "batting5th": "bailepa01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6341,
    "team": "Giants",
    "gameNumber": 34,
    "date": "2024-05-04T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "Ranger SuA¡rez",
    "lhp": True,
    "result": "L",
    "score": "3-14",
    "batting1st": "slateau01",
    "batting2nd": "estrath01",
    "batting3rd": "leeju01",
    "batting4th": "florewi01",
    "batting5th": "chapmma01",
    "batting6th": "solerjo01",
    "batting7th": "murphto04",
    "batting8th": "fitzgty01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6342,
    "team": "Giants",
    "gameNumber": 35,
    "date": "2024-05-05T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "walketa01",
    "lhp": False,
    "result": "L",
    "score": "4-5",
    "batting1st": "leeju01",
    "batting2nd": "wadela01",
    "batting3rd": "florewi01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "estrath01",
    "batting8th": "sabolbl01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6343,
    "team": "Giants",
    "gameNumber": 36,
    "date": "2024-05-06T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "wheelza01",
    "lhp": False,
    "result": "L",
    "score": "1-6",
    "batting1st": "leeju01",
    "batting2nd": "estrath01",
    "batting3rd": "wadela01",
    "batting4th": "florewi01",
    "batting5th": "confomi01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "fitzgty01",
    "batting9th": "reetzja01"
  },
  {
    "id": 6344,
    "team": "Giants",
    "gameNumber": 37,
    "date": "2024-05-07T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "hudsoda01",
    "lhp": False,
    "result": "W",
    "score": "5-0",
    "batting1st": "leeju01",
    "batting2nd": "estrath01",
    "batting3rd": "wadela01",
    "batting4th": "confomi01",
    "batting5th": "florewi01",
    "batting6th": "yastrmi01",
    "batting7th": "chapmma01",
    "batting8th": "sabolbl01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6345,
    "team": "Giants",
    "gameNumber": 38,
    "date": "2024-05-08T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "lambepe01",
    "lhp": False,
    "result": "W",
    "score": "8-6",
    "batting1st": "leeju01",
    "batting2nd": "estrath01",
    "batting3rd": "wadela01",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "ramoshe02",
    "batting8th": "sabolbl01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6346,
    "team": "Giants",
    "gameNumber": 39,
    "date": "2024-05-09T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "quantca01",
    "lhp": False,
    "result": "L",
    "score": "1-9",
    "batting1st": "wadela01",
    "batting2nd": "estrath01",
    "batting3rd": "confomi01",
    "batting4th": "florewi01",
    "batting5th": "yastrmi01",
    "batting6th": "slateau01",
    "batting7th": "sabolbl01",
    "batting8th": "ahmedni01",
    "batting9th": "reetzja01"
  },
  {
    "id": 6347,
    "team": "Giants",
    "gameNumber": 40,
    "date": "2024-05-10T00:00:00",
    "opponent": "Reds",
    "opposingSP": "abbotan01",
    "lhp": True,
    "result": "L",
    "score": "2-4",
    "batting1st": "slateau01",
    "batting2nd": "estrath01",
    "batting3rd": "wadela01",
    "batting4th": "florewi01",
    "batting5th": "chapmma01",
    "batting6th": "ramoshe02",
    "batting7th": "schmica01",
    "batting8th": "fitzgty01",
    "batting9th": "reetzja01"
  },
  {
    "id": 6348,
    "team": "Giants",
    "gameNumber": 41,
    "date": "2024-05-11T00:00:00",
    "opponent": "Reds",
    "opposingSP": "lodolni01",
    "lhp": True,
    "result": "W",
    "score": "5-1",
    "batting1st": "estrath01",
    "batting2nd": "wadela01",
    "batting3rd": "bailepa01",
    "batting4th": "florewi01",
    "batting5th": "ramoshe02",
    "batting6th": "chapmma01",
    "batting7th": "confomi01",
    "batting8th": "schmica01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6349,
    "team": "Giants",
    "gameNumber": 42,
    "date": "2024-05-12T00:00:00",
    "opponent": "Reds",
    "opposingSP": "montafr02",
    "lhp": False,
    "result": "W",
    "score": "6-5",
    "batting1st": "leeju01",
    "batting2nd": "chapmma01",
    "batting3rd": "wadela01",
    "batting4th": "florewi01",
    "batting5th": "yastrmi01",
    "batting6th": "ramoshe02",
    "batting7th": "sabolbl01",
    "batting8th": "schmica01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6350,
    "team": "Giants",
    "gameNumber": 43,
    "date": "2024-05-13T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "yamamyo01",
    "lhp": False,
    "result": "L",
    "score": "4-6",
    "batting1st": "yastrmi01",
    "batting2nd": "estrath01",
    "batting3rd": "chapmma01",
    "batting4th": "wadela01",
    "batting5th": "florewi01",
    "batting6th": "ramoshe02",
    "batting7th": "sabolbl01",
    "batting8th": "matoslu02",
    "batting9th": "schmica01"
  },
  {
    "id": 6351,
    "team": "Giants",
    "gameNumber": 44,
    "date": "2024-05-14T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "stonega01",
    "lhp": False,
    "result": "L",
    "score": "2-10",
    "batting1st": "yastrmi01",
    "batting2nd": "estrath01",
    "batting3rd": "chapmma01",
    "batting4th": "wadela01",
    "batting5th": "florewi01",
    "batting6th": "ramoshe02",
    "batting7th": "sabolbl01",
    "batting8th": "matoslu02",
    "batting9th": "schmica01"
  },
  {
    "id": 6352,
    "team": "Giants",
    "gameNumber": 45,
    "date": "2024-05-15T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "hernael01",
    "lhp": False,
    "result": "W",
    "score": "4-1",
    "batting1st": "yastrmi01",
    "batting2nd": "estrath01",
    "batting3rd": "chapmma01",
    "batting4th": "wadela01",
    "batting5th": "ramoshe02",
    "batting6th": "matoslu02",
    "batting7th": "sabolbl01",
    "batting8th": "schmica01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6353,
    "team": "Giants",
    "gameNumber": 46,
    "date": "2024-05-17T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "feltnry01",
    "lhp": False,
    "result": "W",
    "score": "10-5",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "yastrmi01",
    "batting6th": "ramoshe02",
    "batting7th": "matoslu02",
    "batting8th": "sabolbl01",
    "batting9th": "luciama01"
  },
  {
    "id": 6354,
    "team": "Giants",
    "gameNumber": 47,
    "date": "2024-05-18T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "blachty01",
    "lhp": True,
    "result": "W",
    "score": "14-4",
    "batting1st": "solerjo01",
    "batting2nd": "estrath01",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "matoslu02",
    "batting6th": "ramoshe02",
    "batting7th": "luciama01",
    "batting8th": "yastrmi01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6355,
    "team": "Giants",
    "gameNumber": 48,
    "date": "2024-05-19T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "hudsoda01",
    "lhp": False,
    "result": "W",
    "score": "4-1",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "matoslu02",
    "batting6th": "yastrmi01",
    "batting7th": "ramoshe02",
    "batting8th": "luciama01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6356,
    "team": "Giants",
    "gameNumber": 49,
    "date": "2024-05-21T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "MartA­n PA©rez",
    "lhp": True,
    "result": "L",
    "score": "6-7",
    "batting1st": "solerjo01",
    "batting2nd": "estrath01",
    "batting3rd": "matoslu02",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "ramoshe02",
    "batting7th": "mckenry01",
    "batting8th": "luciama01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6357,
    "team": "Giants",
    "gameNumber": 50,
    "date": "2024-05-22T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "jonesja09",
    "lhp": False,
    "result": "W",
    "score": "9-5",
    "batting1st": "matoslu02",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "ramoshe02",
    "batting8th": "yastrmi01",
    "batting9th": "luciama01"
  },
  {
    "id": 6358,
    "team": "Giants",
    "gameNumber": 51,
    "date": "2024-05-23T00:00:00",
    "opponent": "Pirates",
    "opposingSP": "skenepa01",
    "lhp": False,
    "result": "W",
    "score": "7-6",
    "batting1st": "matoslu02",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "solerjo01",
    "batting6th": "yastrmi01",
    "batting7th": "ramoshe02",
    "batting8th": "casalcu01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6359,
    "team": "Giants",
    "gameNumber": 52,
    "date": "2024-05-24T00:00:00",
    "opponent": "Mets",
    "opposingSP": "scottch01",
    "lhp": False,
    "result": "W",
    "score": "8-7",
    "batting1st": "matoslu02",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "ramoshe02",
    "batting8th": "yastrmi01",
    "batting9th": "luciama01"
  },
  {
    "id": 6360,
    "team": "Giants",
    "gameNumber": 53,
    "date": "2024-05-25T00:00:00",
    "opponent": "Mets",
    "opposingSP": "severlu01",
    "lhp": False,
    "result": "W",
    "score": "7-2",
    "batting1st": "matoslu02",
    "batting2nd": "estrath01",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "yastrmi01",
    "batting7th": "ramoshe02",
    "batting8th": "casalcu01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6361,
    "team": "Giants",
    "gameNumber": 54,
    "date": "2024-05-26T00:00:00",
    "opponent": "Mets",
    "opposingSP": "manaese01",
    "lhp": True,
    "result": "L",
    "score": "3-4",
    "batting1st": "matoslu02",
    "batting2nd": "estrath01",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "solerjo01",
    "batting7th": "ramoshe02",
    "batting8th": "mckenry01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6362,
    "team": "Giants",
    "gameNumber": 55,
    "date": "2024-05-27T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "walketa01",
    "lhp": False,
    "result": "W",
    "score": "8-4",
    "batting1st": "matoslu02",
    "batting2nd": "wadela01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "yastrmi01",
    "batting8th": "ramoshe02",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6363,
    "team": "Giants",
    "gameNumber": 56,
    "date": "2024-05-28T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "wheelza01",
    "lhp": False,
    "result": "W",
    "score": "1-0",
    "batting1st": "matoslu02",
    "batting2nd": "yastrmi01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "wiselbr01",
    "batting8th": "ramoshe02",
    "batting9th": "brooktr01"
  },
  {
    "id": 6364,
    "team": "Giants",
    "gameNumber": 57,
    "date": "2024-05-29T00:00:00",
    "opponent": "Phillies",
    "opposingSP": "Cristopher SA¡nchez",
    "lhp": True,
    "result": "L",
    "score": "1-6",
    "batting1st": "matoslu02",
    "batting2nd": "luciama01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "solerjo01",
    "batting7th": "ramoshe02",
    "batting8th": "fitzgty01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6365,
    "team": "Giants",
    "gameNumber": 58,
    "date": "2024-05-31T00:00:00",
    "opponent": "Yankees",
    "opposingSP": "stromma01",
    "lhp": False,
    "result": "L",
    "score": "2-6",
    "batting1st": "matoslu02",
    "batting2nd": "yastrmi01",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "wiselbr01",
    "batting8th": "ramoshe02",
    "batting9th": "brooktr01"
  },
  {
    "id": 6366,
    "team": "Giants",
    "gameNumber": 59,
    "date": "2024-06-01T00:00:00",
    "opponent": "Yankees",
    "opposingSP": "poteeco01",
    "lhp": False,
    "result": "L",
    "score": "3-7",
    "batting1st": "matoslu02",
    "batting2nd": "florewi01",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "yastrmi01",
    "batting6th": "ramoshe02",
    "batting7th": "brooktr01",
    "batting8th": "schmica01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6367,
    "team": "Giants",
    "gameNumber": 60,
    "date": "2024-06-02T00:00:00",
    "opponent": "Yankees",
    "opposingSP": "cortene01",
    "lhp": True,
    "result": "L",
    "score": "5-7",
    "batting1st": "ramoshe02",
    "batting2nd": "wiselbr01",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "solerjo01",
    "batting6th": "matoslu02",
    "batting7th": "schmica01",
    "batting8th": "fitzgty01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6368,
    "team": "Giants",
    "gameNumber": 61,
    "date": "2024-06-03T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "nelsory01",
    "lhp": False,
    "result": "L",
    "score": "2-4",
    "batting1st": "wiselbr01",
    "batting2nd": "bailepa01",
    "batting3rd": "chapmma01",
    "batting4th": "confomi01",
    "batting5th": "ramoshe02",
    "batting6th": "solerjo01",
    "batting7th": "yastrmi01",
    "batting8th": "schmica01",
    "batting9th": "brooktr01"
  },
  {
    "id": 6369,
    "team": "Giants",
    "gameNumber": 62,
    "date": "2024-06-04T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "walstbl01",
    "lhp": True,
    "result": "L",
    "score": "5-8",
    "batting1st": "ramoshe02",
    "batting2nd": "estrath01",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "florewi01",
    "batting8th": "schmica01",
    "batting9th": "matoslu02"
  },
  {
    "id": 6370,
    "team": "Giants",
    "gameNumber": 63,
    "date": "2024-06-05T00:00:00",
    "opponent": "Diamondbacks",
    "opposingSP": "montgjo01",
    "lhp": True,
    "result": "W",
    "score": "9-3",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "estrath01",
    "batting4th": "chapmma01",
    "batting5th": "solerjo01",
    "batting6th": "florewi01",
    "batting7th": "yastrmi01",
    "batting8th": "fitzgty01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6371,
    "team": "Giants",
    "gameNumber": 64,
    "date": "2024-06-07T00:00:00",
    "opponent": "Rangers",
    "opposingSP": "lorenmi01",
    "lhp": False,
    "result": "W",
    "score": "5-2",
    "batting1st": "ramoshe02",
    "batting2nd": "bailepa01",
    "batting3rd": "chapmma01",
    "batting4th": "confomi01",
    "batting5th": "solerjo01",
    "batting6th": "florewi01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6372,
    "team": "Giants",
    "gameNumber": 65,
    "date": "2024-06-08T00:00:00",
    "opponent": "Rangers",
    "opposingSP": "heanean01",
    "lhp": True,
    "result": "W",
    "score": "3-1",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "estrath01",
    "batting8th": "casalcu01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6373,
    "team": "Giants",
    "gameNumber": 66,
    "date": "2024-06-09T00:00:00",
    "opponent": "Rangers",
    "opposingSP": "eovalna01",
    "lhp": False,
    "result": "L",
    "score": "2-7",
    "batting1st": "ramoshe02",
    "batting2nd": "bailepa01",
    "batting3rd": "florewi01",
    "batting4th": "confomi01",
    "batting5th": "estrath01",
    "batting6th": "yastrmi01",
    "batting7th": "wiselbr01",
    "batting8th": "schmica01",
    "batting9th": "brooktr01"
  },
  {
    "id": 6374,
    "team": "Giants",
    "gameNumber": 67,
    "date": "2024-06-10T00:00:00",
    "opponent": "Astros",
    "opposingSP": "arrigsp01",
    "lhp": False,
    "result": "W",
    "score": "4-3",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "confomi01",
    "batting5th": "solerjo01",
    "batting6th": "yastrmi01",
    "batting7th": "estrath01",
    "batting8th": "brooktr01",
    "batting9th": "schmica01"
  },
  {
    "id": 6375,
    "team": "Giants",
    "gameNumber": 68,
    "date": "2024-06-11T00:00:00",
    "opponent": "Astros",
    "opposingSP": "blancro01",
    "lhp": False,
    "result": "L",
    "score": "1-3",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "florewi01",
    "batting7th": "solerjo01",
    "batting8th": "yastrmi01",
    "batting9th": "estrath01"
  },
  {
    "id": 6376,
    "team": "Giants",
    "gameNumber": 69,
    "date": "2024-06-12T00:00:00",
    "opponent": "Astros",
    "opposingSP": "valdefr01",
    "lhp": True,
    "result": "W",
    "score": "5-3",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "solerjo01",
    "batting7th": "wiselbr01",
    "batting8th": "estrath01",
    "batting9th": "yastrmi01"
  },
  {
    "id": 6377,
    "team": "Giants",
    "gameNumber": 70,
    "date": "2024-06-14T00:00:00",
    "opponent": "Angels",
    "opposingSP": "anderty01",
    "lhp": True,
    "result": "L",
    "score": "6-8",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "solerjo01",
    "batting7th": "confomi01",
    "batting8th": "estrath01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6378,
    "team": "Giants",
    "gameNumber": 71,
    "date": "2024-06-15T00:00:00",
    "opponent": "Angels",
    "opposingSP": "sandopa02",
    "lhp": True,
    "result": "L",
    "score": "3-4",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "solerjo01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "ahmedni01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6379,
    "team": "Giants",
    "gameNumber": 72,
    "date": "2024-06-16T00:00:00",
    "opponent": "Angels",
    "opposingSP": "joycebe01",
    "lhp": False,
    "result": "W",
    "score": "13-6",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "florewi01",
    "batting8th": "yastrmi01",
    "batting9th": "estrath01"
  },
  {
    "id": 6380,
    "team": "Giants",
    "gameNumber": 73,
    "date": "2024-06-17T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "assadja01",
    "lhp": False,
    "result": "W",
    "score": "7-6",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "brooktr01"
  },
  {
    "id": 6381,
    "team": "Giants",
    "gameNumber": 74,
    "date": "2024-06-18T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "steelju01",
    "lhp": True,
    "result": "L",
    "score": "2-5",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "estrath01",
    "batting6th": "solerjo01",
    "batting7th": "ahmedni01",
    "batting8th": "yastrmi01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6382,
    "team": "Giants",
    "gameNumber": 75,
    "date": "2024-06-19T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "hendrky01",
    "lhp": False,
    "result": "L",
    "score": "5-6",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "brooktr01"
  },
  {
    "id": 6383,
    "team": "Giants",
    "gameNumber": 76,
    "date": "2024-06-20T00:00:00",
    "opponent": "Cardinals",
    "opposingSP": "pallaan01",
    "lhp": False,
    "result": "L",
    "score": "5-6",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "solerjo01",
    "batting7th": "florewi01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6384,
    "team": "Giants",
    "gameNumber": 77,
    "date": "2024-06-22T00:00:00",
    "opponent": "Cardinals",
    "opposingSP": "mikolmi01",
    "lhp": False,
    "result": "L",
    "score": "4-9",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "villada01",
    "batting9th": "matoslu02"
  },
  {
    "id": 6385,
    "team": "Giants",
    "gameNumber": 78,
    "date": "2024-06-23T00:00:00",
    "opponent": "Cardinals",
    "opposingSP": "grayso01",
    "lhp": False,
    "result": "L",
    "score": "3-5",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "brooktr01",
    "batting9th": "slateau01"
  },
  {
    "id": 6386,
    "team": "Giants",
    "gameNumber": 79,
    "date": "2024-06-24T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "steelju01",
    "lhp": True,
    "result": "W",
    "score": "5-4",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "estrath01",
    "batting7th": "matoslu02",
    "batting8th": "casalcu01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6387,
    "team": "Giants",
    "gameNumber": 80,
    "date": "2024-06-25T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "hendrky01",
    "lhp": False,
    "result": "W",
    "score": "5-1",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "solerjo01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "villada01",
    "batting9th": "matoslu02"
  },
  {
    "id": 6388,
    "team": "Giants",
    "gameNumber": 81,
    "date": "2024-06-26T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "wesneha01",
    "lhp": False,
    "result": "W",
    "score": "4-3",
    "batting1st": "wiselbr01",
    "batting2nd": "ramoshe02",
    "batting3rd": "chapmma01",
    "batting4th": "bailepa01",
    "batting5th": "solerjo01",
    "batting6th": "estrath01",
    "batting7th": "confomi01",
    "batting8th": "villada01",
    "batting9th": "matoslu02"
  },
  {
    "id": 6389,
    "team": "Giants",
    "gameNumber": 82,
    "date": "2024-06-27T00:00:00",
    "opponent": "Cubs",
    "opposingSP": "imanash01",
    "lhp": True,
    "result": "L",
    "score": "3-5",
    "batting1st": "slateau01",
    "batting2nd": "ramoshe02",
    "batting3rd": "florewi01",
    "batting4th": "chapmma01",
    "batting5th": "solerjo01",
    "batting6th": "matoslu02",
    "batting7th": "estrath01",
    "batting8th": "ahmedni01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6390,
    "team": "Giants",
    "gameNumber": 83,
    "date": "2024-06-28T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "knackla01",
    "lhp": False,
    "result": "W",
    "score": "5-3",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "matoslu02",
    "batting8th": "wiselbr01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6391,
    "team": "Giants",
    "gameNumber": 84,
    "date": "2024-06-29T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "glasnty01",
    "lhp": False,
    "result": "L",
    "score": "7-14",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "matoslu02",
    "batting8th": "wiselbr01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6392,
    "team": "Giants",
    "gameNumber": 85,
    "date": "2024-06-30T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "paxtoja01",
    "lhp": True,
    "result": "W",
    "score": "10-4",
    "batting1st": "solerjo01",
    "batting2nd": "slateau01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "matoslu02",
    "batting7th": "villada01",
    "batting8th": "ahmedni01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6393,
    "team": "Giants",
    "gameNumber": 86,
    "date": "2024-07-02T00:00:00",
    "opponent": "Braves",
    "opposingSP": "Reynaldo LA³pez",
    "lhp": False,
    "result": "W",
    "score": "5-3",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "wiselbr01",
    "batting8th": "yastrmi01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6394,
    "team": "Giants",
    "gameNumber": 87,
    "date": "2024-07-03T00:00:00",
    "opponent": "Braves",
    "opposingSP": "salech01",
    "lhp": True,
    "result": "L",
    "score": "1-3",
    "batting1st": "solerjo01",
    "batting2nd": "slateau01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "matoslu02",
    "batting6th": "villada01",
    "batting7th": "ahmedni01",
    "batting8th": "casalcu01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6395,
    "team": "Giants",
    "gameNumber": 88,
    "date": "2024-07-04T00:00:00",
    "opponent": "Braves",
    "opposingSP": "mortoch02",
    "lhp": False,
    "result": "W",
    "score": "4-2",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "yastrmi01",
    "batting8th": "wiselbr01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6396,
    "team": "Giants",
    "gameNumber": 89,
    "date": "2024-07-05T00:00:00",
    "opponent": "Guardians",
    "opposingSP": "bibeeta01",
    "lhp": False,
    "result": "W",
    "score": "4-2",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "yastrmi01",
    "batting8th": "wiselbr01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6397,
    "team": "Giants",
    "gameNumber": 90,
    "date": "2024-07-06T00:00:00",
    "opponent": "Guardians",
    "opposingSP": "allenlo01",
    "lhp": True,
    "result": "L",
    "score": "4-5",
    "batting1st": "solerjo01",
    "batting2nd": "slateau01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "matoslu02",
    "batting6th": "fitzgty01",
    "batting7th": "casalcu01",
    "batting8th": "ahmedni01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6398,
    "team": "Giants",
    "gameNumber": 91,
    "date": "2024-07-07T00:00:00",
    "opponent": "Guardians",
    "opposingSP": "carraca01",
    "lhp": False,
    "result": "L",
    "score": "4-5",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "yastrmi01",
    "batting8th": "wiselbr01",
    "batting9th": "ahmedni01"
  },
  {
    "id": 6399,
    "team": "Giants",
    "gameNumber": 92,
    "date": "2024-07-09T00:00:00",
    "opponent": "Blue Jays",
    "opposingSP": "kikucyu01",
    "lhp": True,
    "result": "W",
    "score": "4-3",
    "batting1st": "estrath01",
    "batting2nd": "ramoshe02",
    "batting3rd": "confomi01",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "bailepa01",
    "batting7th": "matoslu02",
    "batting8th": "fitzgty01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6400,
    "team": "Giants",
    "gameNumber": 93,
    "date": "2024-07-10T00:00:00",
    "opponent": "Blue Jays",
    "opposingSP": "bassich01",
    "lhp": False,
    "result": "L",
    "score": "6-10",
    "batting1st": "wadela01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "wiselbr01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6401,
    "team": "Giants",
    "gameNumber": 94,
    "date": "2024-07-11T00:00:00",
    "opponent": "Blue Jays",
    "opposingSP": "gausmke01",
    "lhp": False,
    "result": "L",
    "score": "3-5",
    "batting1st": "solerjo01",
    "batting2nd": "bailepa01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "florewi01",
    "batting8th": "estrath01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6402,
    "team": "Giants",
    "gameNumber": 95,
    "date": "2024-07-12T00:00:00",
    "opponent": "Twins",
    "opposingSP": "ryanjo04",
    "lhp": False,
    "result": "W",
    "score": "7-1",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6403,
    "team": "Giants",
    "gameNumber": 96,
    "date": "2024-07-13T00:00:00",
    "opponent": "Twins",
    "opposingSP": "woodssi01",
    "lhp": False,
    "result": "L",
    "score": "2-4",
    "batting1st": "solerjo01",
    "batting2nd": "wiselbr01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "florewi01",
    "batting8th": "yastrmi01",
    "batting9th": "estrath01"
  },
  {
    "id": 6404,
    "team": "Giants",
    "gameNumber": 97,
    "date": "2024-07-14T00:00:00",
    "opponent": "Twins",
    "opposingSP": "paddach01",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "confomi01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6405,
    "team": "Giants",
    "gameNumber": 98,
    "date": "2024-07-19T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "quantca01",
    "lhp": False,
    "result": "L",
    "score": "3-7",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "confomi01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "estrath01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6406,
    "team": "Giants",
    "gameNumber": 99,
    "date": "2024-07-20T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "freelky01",
    "lhp": True,
    "result": "L",
    "score": "3-4",
    "batting1st": "solerjo01",
    "batting2nd": "matoslu02",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "florewi01",
    "batting6th": "estrath01",
    "batting7th": "yastrmi01",
    "batting8th": "casalcu01",
    "batting9th": "fitzgty01"
  },
  {
    "id": 6407,
    "team": "Giants",
    "gameNumber": 100,
    "date": "2024-07-21T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "feltnry01",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "confomi01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "fitzgty01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6408,
    "team": "Giants",
    "gameNumber": 101,
    "date": "2024-07-22T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "ryanri01",
    "lhp": False,
    "result": "L",
    "score": "2-3",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "confomi01",
    "batting6th": "chapmma01",
    "batting7th": "yastrmi01",
    "batting8th": "fitzgty01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6409,
    "team": "Giants",
    "gameNumber": 102,
    "date": "2024-07-23T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "knackla01",
    "lhp": False,
    "result": "L",
    "score": "2-5",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "chapmma01",
    "batting6th": "confomi01",
    "batting7th": "fitzgty01",
    "batting8th": "yastrmi01",
    "batting9th": "estrath01"
  },
  {
    "id": 6410,
    "team": "Giants",
    "gameNumber": 103,
    "date": "2024-07-24T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "glasnty01",
    "lhp": False,
    "result": "W",
    "score": "8-3",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "fitzgty01",
    "batting7th": "yastrmi01",
    "batting8th": "casalcu01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6411,
    "team": "Giants",
    "gameNumber": 104,
    "date": "2024-07-25T00:00:00",
    "opponent": "Dodgers",
    "opposingSP": "kershcl01",
    "lhp": True,
    "result": "L",
    "score": "4-6",
    "batting1st": "solerjo01",
    "batting2nd": "fitzgty01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "villada01",
    "batting7th": "estrath01",
    "batting8th": "yastrmi01",
    "batting9th": "hillde01"
  },
  {
    "id": 6412,
    "team": "Giants",
    "gameNumber": 105,
    "date": "2024-07-26T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "freelky01",
    "lhp": True,
    "result": "W",
    "score": "11-4",
    "batting1st": "solerjo01",
    "batting2nd": "fitzgty01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "villada01",
    "batting6th": "yastrmi01",
    "batting7th": "bailepa01",
    "batting8th": "schmica01",
    "batting9th": "hillde01"
  },
  {
    "id": 6413,
    "team": "Giants",
    "gameNumber": 106,
    "date": "2024-07-27T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "feltnry01",
    "lhp": False,
    "result": "W",
    "score": "4-1",
    "batting1st": "solerjo01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "bailepa01",
    "batting5th": "fitzgty01",
    "batting6th": "confomi01",
    "batting7th": "chapmma01",
    "batting8th": "yastrmi01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6414,
    "team": "Giants",
    "gameNumber": 107,
    "date": "2024-07-27T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "gordota01",
    "lhp": False,
    "result": "W",
    "score": "5-0",
    "batting1st": "solerjo01",
    "batting2nd": "yastrmi01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "fitzgty01",
    "batting6th": "chapmma01",
    "batting7th": "wiselbr01",
    "batting8th": "villada01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6415,
    "team": "Giants",
    "gameNumber": 108,
    "date": "2024-07-28T00:00:00",
    "opponent": "Rockies",
    "opposingSP": "gombeau01",
    "lhp": True,
    "result": "W",
    "score": "5-4",
    "batting1st": "solerjo01",
    "batting2nd": "schmica01",
    "batting3rd": "fitzgty01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "yastrmi01",
    "batting7th": "villada01",
    "batting8th": "confomi01",
    "batting9th": "hillde01"
  },
  {
    "id": 6416,
    "team": "Giants",
    "gameNumber": 109,
    "date": "2024-07-30T00:00:00",
    "opponent": "Athletics",
    "opposingSP": "searsjp01",
    "lhp": True,
    "result": "L",
    "score": "2-5",
    "batting1st": "fitzgty01",
    "batting2nd": "schmica01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "luciama01",
    "batting7th": "yastrmi01",
    "batting8th": "villada01",
    "batting9th": "hillde01"
  },
  {
    "id": 6417,
    "team": "Giants",
    "gameNumber": 110,
    "date": "2024-07-31T00:00:00",
    "opponent": "Athletics",
    "opposingSP": "stripro01",
    "lhp": False,
    "result": "W",
    "score": "1-0",
    "batting1st": "wadela01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "fitzgty01",
    "batting7th": "yastrmi01",
    "batting8th": "luciama01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6418,
    "team": "Giants",
    "gameNumber": 111,
    "date": "2024-08-02T00:00:00",
    "opponent": "Reds",
    "opposingSP": "abbotan01",
    "lhp": True,
    "result": "W",
    "score": "3-0",
    "batting1st": "fitzgty01",
    "batting2nd": "canhama01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "encarje01",
    "batting7th": "confomi01",
    "batting8th": "schmica01",
    "batting9th": "luciama01"
  },
  {
    "id": 6419,
    "team": "Giants",
    "gameNumber": 112,
    "date": "2024-08-03T00:00:00",
    "opponent": "Reds",
    "opposingSP": "greenhu01",
    "lhp": False,
    "result": "L",
    "score": "4-6",
    "batting1st": "wadela01",
    "batting2nd": "ramoshe02",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "fitzgty01",
    "batting7th": "yastrmi01",
    "batting8th": "luciama01",
    "batting9th": "schmica01"
  },
  {
    "id": 6420,
    "team": "Giants",
    "gameNumber": 113,
    "date": "2024-08-04T00:00:00",
    "opponent": "Reds",
    "opposingSP": "spierca01",
    "lhp": False,
    "result": "W",
    "score": "8-2",
    "batting1st": "wadela01",
    "batting2nd": "fitzgty01",
    "batting3rd": "bailepa01",
    "batting4th": "chapmma01",
    "batting5th": "confomi01",
    "batting6th": "encarje01",
    "batting7th": "yastrmi01",
    "batting8th": "casalcu01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6421,
    "team": "Giants",
    "gameNumber": 114,
    "date": "2024-08-05T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "corbipa01",
    "lhp": True,
    "result": "W",
    "score": "4-1",
    "batting1st": "fitzgty01",
    "batting2nd": "canhama01",
    "batting3rd": "confomi01",
    "batting4th": "chapmma01",
    "batting5th": "schmica01",
    "batting6th": "encarje01",
    "batting7th": "bailepa01",
    "batting8th": "luciama01",
    "batting9th": "yastrmi01"
  },
  {
    "id": 6422,
    "team": "Giants",
    "gameNumber": 115,
    "date": "2024-08-06T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "gorema01",
    "lhp": True,
    "result": "L",
    "score": "5-11",
    "batting1st": "fitzgty01",
    "batting2nd": "ramoshe02",
    "batting3rd": "wadela01",
    "batting4th": "chapmma01",
    "batting5th": "canhama01",
    "batting6th": "confomi01",
    "batting7th": "encarje01",
    "batting8th": "bailepa01",
    "batting9th": "schmica01"
  },
  {
    "id": 6423,
    "team": "Giants",
    "gameNumber": 116,
    "date": "2024-08-07T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "irvinja01",
    "lhp": False,
    "result": "W",
    "score": "7-4",
    "batting1st": "wadela01",
    "batting2nd": "ramoshe02",
    "batting3rd": "confomi01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "fitzgty01",
    "batting7th": "yastrmi01",
    "batting8th": "encarje01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6424,
    "team": "Giants",
    "gameNumber": 117,
    "date": "2024-08-08T00:00:00",
    "opponent": "Nationals",
    "opposingSP": "herzdj01",
    "lhp": True,
    "result": "W",
    "score": "9-5",
    "batting1st": "fitzgty01",
    "batting2nd": "ramoshe02",
    "batting3rd": "confomi01",
    "batting4th": "chapmma01",
    "batting5th": "canhama01",
    "batting6th": "encarje01",
    "batting7th": "yastrmi01",
    "batting8th": "schmica01",
    "batting9th": "reetzja01"
  },
  {
    "id": 6425,
    "team": "Giants",
    "gameNumber": 118,
    "date": "2024-08-09T00:00:00",
    "opponent": "Tigers",
    "opposingSP": "briesbe01",
    "lhp": False,
    "result": "W",
    "score": "3-2",
    "batting1st": "wadela01",
    "batting2nd": "fitzgty01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "canhama01",
    "batting8th": "wiselbr01",
    "batting9th": "casalcu01"
  },
  {
    "id": 6426,
    "team": "Giants",
    "gameNumber": 119,
    "date": "2024-08-10T00:00:00",
    "opponent": "Tigers",
    "opposingSP": "faedoal01",
    "lhp": False,
    "result": "W",
    "score": "3-1",
    "batting1st": "fitzgty01",
    "batting2nd": "ramoshe02",
    "batting3rd": "confomi01",
    "batting4th": "chapmma01",
    "batting5th": "bailepa01",
    "batting6th": "canhama01",
    "batting7th": "yastrmi01",
    "batting8th": "encarje01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6427,
    "team": "Giants",
    "gameNumber": 120,
    "date": "2024-08-11T00:00:00",
    "opponent": "Tigers",
    "opposingSP": "monteke01",
    "lhp": False,
    "result": "L",
    "score": "4-5",
    "batting1st": "fitzgty01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "bailepa01",
    "batting8th": "encarje01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6428,
    "team": "Giants",
    "gameNumber": 121,
    "date": "2024-08-12T00:00:00",
    "opponent": "Braves",
    "opposingSP": "salech01",
    "lhp": True,
    "result": "L",
    "score": "0-1",
    "batting1st": "fitzgty01",
    "batting2nd": "canhama01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "encarje01",
    "batting6th": "yastrmi01",
    "batting7th": "luciama01",
    "batting8th": "bailepa01",
    "batting9th": "schmica01"
  },
  {
    "id": 6429,
    "team": "Giants",
    "gameNumber": 122,
    "date": "2024-08-13T00:00:00",
    "opponent": "Braves",
    "opposingSP": "mortoch02",
    "lhp": False,
    "result": "L",
    "score": "3-4",
    "batting1st": "fitzgty01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "bailepa01",
    "batting8th": "encarje01",
    "batting9th": "wiselbr01"
  },
  {
    "id": 6430,
    "team": "Giants",
    "gameNumber": 123,
    "date": "2024-08-14T00:00:00",
    "opponent": "Braves",
    "opposingSP": "holmegr01",
    "lhp": False,
    "result": "L",
    "score": "2-13",
    "batting1st": "fitzgty01",
    "batting2nd": "wadela01",
    "batting3rd": "ramoshe02",
    "batting4th": "confomi01",
    "batting5th": "chapmma01",
    "batting6th": "yastrmi01",
    "batting7th": "bailepa01",
    "batting8th": "wiselbr01",
    "batting9th": "mccragr01"
  },
  {
    "id": 7228,
    "team": "Giants",
    "gameNumber": 124,
    "date": "2024-08-15T00:00:00",
    "opponent": "Braves",
    "opposingSP": "friedma01",
    "lhp": True,
    "result": "W",
    "score": "6-0",
    "batting1st": "fitzgty01",
    "batting2nd": "canhama01",
    "batting3rd": "ramoshe02",
    "batting4th": "chapmma01",
    "batting5th": "encarje01",
    "batting6th": "yastrmi01",
    "batting7th": "schmica01",
    "batting8th": "casalcu01",
    "batting9th": "mccragr01"
  }
]



def extract_recent_lineups(all_lineups, num_recent_games=10):
    # Sort the lineups by 'gameNumber' in descending order to get the most recent games first
    sorted_lineups = sorted(all_lineups, key=lambda x: x['gameNumber'], reverse=True)
    
    # Extract the most recent `num_recent_games` lineups
    recent_lineups = sorted_lineups[:num_recent_games]
    
    return recent_lineups

def predict_lineup(recent_lineups, all_lineups, facing_lhp, weight_recent=5):
    # Filter lineups by LHP/RHP
    relevant_lineups = [lineup for lineup in all_lineups if lineup['lhp'] == facing_lhp]
    recent_relevant_lineups = [lineup for lineup in recent_lineups if lineup['lhp'] == facing_lhp]
    
    # Gather players who appeared in the last 10 games
    recent_players = set()
    for lineup in recent_relevant_lineups:
        for i in range(1, 10):
            for key in lineup:
                if key.startswith(f'batting{i}'):
                    recent_players.add(lineup[key])

    # Aggregate batting positions for all relevant lineups, giving extra weight to recent lineups
    batting_positions = {f'batting{i}': [] for i in range(1, 10)}
    
    # Add recent lineups with weight
    for lineup in recent_relevant_lineups:
        for i in range(1, 10):
            for key in lineup:
                if key.startswith(f'batting{i}'):
                    batting_positions[f'batting{i}'].extend([lineup[key]] * weight_recent)
    
    # Add older lineups
    for lineup in relevant_lineups:
        for i in range(1, 10):
            for key in lineup:
                if key.startswith(f'batting{i}'):
                    batting_positions[f'batting{i}'].append(lineup[key])
    
    # Predict the lineup, ensuring no duplicates and restricting to recent players
    predicted_lineup = {}
    selected_players = set()

    for i in range(1, 10):
        candidates = [player for player in Counter(batting_positions[f'batting{i}']).most_common() if player[0] in recent_players and player[0] not in selected_players]
        if candidates:
            most_common_player = candidates[0][0]
            predicted_lineup[f'batting{i}'] = most_common_player
            selected_players.add(most_common_player)
        else:
            predicted_lineup[f'batting{i}'] = None  # No eligible player for this position
    
    return predicted_lineup

# Example usage   
# Extract the 10 most recent lineups
recent_lineups = extract_recent_lineups(all_lineups, num_recent_games=10)

facing_lhp = True  # Next game is against a LHP
predicted_lineup_lhp = predict_lineup(recent_lineups, all_lineups, facing_lhp)
print("vs LHP:", predicted_lineup_lhp)

facing_lhp = False  # Next game is against a RHP
predicted_lineup_rhp = predict_lineup(recent_lineups, all_lineups, facing_lhp)
print("vs RHP:", predicted_lineup_rhp)
